### ISSUE TITLE
nlu模块训练过程中出现ValueError: The first argument to `Layer.call` must always be passed.

### ISSUE THREAD

**Issue by LakersUpAma** [cc2017111/KG#2]
train的112行distributed_train_step()出现这个问题，
关联问题有ber_model的42行embedding_outputs，
不知道能否解决

**Comment by cc2017111** [comment]
出现这个问题首先请确保参数正确传递，检查参数个数是否与模型的需求一致，shape是否正确https://github.com/cc2017111/KG/blob/801cf3c20c52ec2a187062dc7f026493faf4a981/NLU/intent_recognition/Bert/engines/train.py#L69，以及预处理的过程。请提供具体报错信息，以供查看。

**Comment by LakersUpAma** [comment]
辛苦您，我对代码的改动就是把分布式tf.distribute.MirroredStrategy(devices=["GPU:0", "GPU:1", "GPU:2"])改为了tf.distribute.MirroredStrategy()，在main函数加入os.environ["CUDA_VISIBLE_DEVICES"] = '-1'。
数据集都是代码中已有的医疗问答对。运行后出现以下问题：

Traceback (most recent call last):
  File "D:/PyCharm/PycharmProjects/MedicalKnowledgeGraph/NLU/intent_recognition/Bert/engines/main.py", line 65, in <module>
    train(configs, dataManager, logger)
  File "D:\PyCharm\PycharmProjects\MedicalKnowledgeGraph\NLU\intent_recognition\Bert\engines\train.py", line 119, in train
    y_train_batch = y_train_batch.values[0].numpy()
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 401, in __getattr__
    self.__getattribute__(name)
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'values'

**Comment by LakersUpAma** [comment]
辛苦您，我对代码的改动就是把分布式tf.distribute.MirroredStrategy(devices=["GPU:0", "GPU:1", "GPU:2"])改为了tf.distribute.MirroredStrategy()，在main函数加入os.environ["CUDA_VISIBLE_DEVICES"] = '-1'。
数据集都是代码中已有的医疗问答对。运行后出现以下问题：

Traceback (most recent call last):
  File "D:/PyCharm/PycharmProjects/MedicalKnowledgeGraph/NLU/intent_recognition/Bert/engines/main.py", line 65, in <module>
    train(configs, dataManager, logger)
  File "D:\PyCharm\PycharmProjects\MedicalKnowledgeGraph\NLU\intent_recognition\Bert\engines\train.py", line 119, in train
    y_train_batch = y_train_batch.values[0].numpy()
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 401, in __getattr__
    self.__getattribute__(name)
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'values'

**Comment by LakersUpAma** [comment]
把119行和120行的value删掉后出现以下问题：
Traceback (most recent call last):
  File "D:/PyCharm/PycharmProjects/MedicalKnowledgeGraph/NLU/intent_recognition/Bert/engines/main.py", line 65, in <module>
    train(configs, dataManager, logger)
  File "D:\PyCharm\PycharmProjects\MedicalKnowledgeGraph\NLU\intent_recognition\Bert\engines\train.py", line 126, in train
    _, outputs = distributed_train_step(X)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\def_function.py", line 763, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    D:\PyCharm\PycharmProjects\MedicalKnowledgeGraph\NLU\intent_recognition\Bert\engines\train.py:99 distributed_train_step  *
        per_replica_losses, outputs = strategy.run(train_step, args=(inputs,))
    D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\distribute\mirrored_run.py:104 call_for_each_replica  *
        return _call_for_each_replica(strategy, fn, args, kwargs)
    D:\PyCharm\PycharmProjects\MedicalKnowledgeGraph\NLU\intent_recognition\Bert\engines\train.py:75 train_step  *
        outputs = model.call(input_ids=X_train_batch, input_mask=att_mask_train_batch, token_ids=token_type_ids_train_batch, training=True)
    D:\PyCharm\PycharmProjects\MedicalKnowledgeGraph\NLU\intent_recognition\Bert\engines\bert_model.py:42 call  *
        embedding_outputs = self.bert_layers(inputs=input_ids, attention_mask=input_mask, token_type_ids=token_ids)
    D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:960 __call__  **
        inputs, args, kwargs = self._split_out_first_arg(args, kwargs)
    D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:2977 _split_out_first_arg
        raise ValueError(

    ValueError: The first argument to `Layer.call` must always be passed.

**Comment by LakersUpAma** [comment]
train_step方法中打印inputs形状如下：
    print(X_train_batch, y_train_batch, att_mask_train_batch, token_type_ids_train_batch)
    Tensor("args:0", shape=(16, 512), dtype=int32) Tensor("args_1:0", shape=(16,), dtype=int32) Tensor("args_2:0", shape=(16, 512), dtype=int32) Tensor("args_3:0", shape=(16, 512), dtype=int32)

**Comment by loveleaves** [comment]
> 把119行和120行的value删掉后出现以下问题： Traceback (most recent call last): File "D:/PyCharm/PycharmProjects/MedicalKnowledgeGraph/NLU/intent_recognition/Bert/engines/main.py", line 65, in train(configs, dataManager, logger) File "D:\PyCharm\PycharmProjects\MedicalKnowledgeGraph\NLU\intent_recognition\Bert\engines\train.py", line 126, in train _, outputs = distributed_train_step(X) File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\def_function.py", line 889, in **call** result = self._call(*args, **kwds) File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\def_function.py", line 933, in _call self._initialize(args, kwds, add_initializers_to=initializers) File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\def_function.py", line 763, in _initialize self._stateful_fn._get_concrete_function_internal_garbage_collected( # pylint: disable=protected-access File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\function.py", line 3050, in _get_concrete_function_internal_garbage_collected graph_function, _ = self._maybe_define_function(args, kwargs) File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\function.py", line 3444, in _maybe_define_function graph_function = self._create_graph_function(args, kwargs) File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\function.py", line 3279, in _create_graph_function func_graph_module.func_graph_from_py_func( File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\func_graph.py", line 999, in func_graph_from_py_func func_outputs = python_func(*func_args, **func_kwargs) File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\eager\def_function.py", line 672, in wrapped_fn out = weak_wrapped_fn().**wrapped**(*args, **kwds) File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in wrapper raise e.ag_error_metadata.to_exception(e) ValueError: in user code:
> 
> ```
> D:\PyCharm\PycharmProjects\MedicalKnowledgeGraph\NLU\intent_recognition\Bert\engines\train.py:99 distributed_train_step  *
>     per_replica_losses, outputs = strategy.run(train_step, args=(inputs,))
> D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\distribute\mirrored_run.py:104 call_for_each_replica  *
>     return _call_for_each_replica(strategy, fn, args, kwargs)
> D:\PyCharm\PycharmProjects\MedicalKnowledgeGraph\NLU\intent_recognition\Bert\engines\train.py:75 train_step  *
>     outputs = model.call(input_ids=X_train_batch, input_mask=att_mask_train_batch, token_ids=token_type_ids_train_batch, training=True)
> D:\PyCharm\PycharmProjects\MedicalKnowledgeGraph\NLU\intent_recognition\Bert\engines\bert_model.py:42 call  *
>     embedding_outputs = self.bert_layers(inputs=input_ids, attention_mask=input_mask, token_type_ids=token_ids)
> D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:960 __call__  **
>     inputs, args, kwargs = self._split_out_first_arg(args, kwargs)
> D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:2977 _split_out_first_arg
>     raise ValueError(
> 
> ValueError: The first argument to `Layer.call` must always be passed.
> ```

这个是transformer接收参数的问题。你可以查看报错的“D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\base_layer.py“大概2977的“_split_out_first_arg”函数，我的包版本对应的函数如下：
```
def _split_out_first_arg(self, args, kwargs):
    # Grab the argument corresponding to the first argument in the
    # layer's `call` method spec. This will either be the first positional
    # argument, or it will be provided as a keyword argument.
    if args:
      inputs = args[0]
      args = args[1:]
    elif self._call_fn_args[0] in kwargs:
      kwargs = copy.copy(kwargs)
      inputs = kwargs.pop(self._call_fn_args[0])
    else:
      raise ValueError(
          'The first argument to `Layer.call` must always be passed.')
    return inputs, args, kwargs
```
如果只是解决这个报错，可以把bert_model.py中的42行的如下行
embedding_outputs = self.bert_layers(inputs=input_ids, attention_mask=input_mask, token_type_ids=token_ids)
改为如下：
embedding_outputs = self.bert_layers((input_ids, input_mask, token_ids))
或者简单的改为如下：
embedding_outputs = self.bert_layers(input_ids)
这样应该就可以解决这个报错，具体原因可以查看base_layer.py的源码
